#ifndef SUBJECTLOADBALANCE_GLOBAL_H
#define SUBJECTLOADBALANCE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SUBJECTLOADBALANCE_LIBRARY)
#  define SUBJECTLOADBALANCE_EXPORT Q_DECL_EXPORT
#else
#  define SUBJECTLOADBALANCE_EXPORT Q_DECL_IMPORT
#endif

#endif // SUBJECTLOADBALANCE_GLOBAL_H
